name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: 961477247679
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

           # Step 2: Debug OIDC Setup
      - name: Debug OIDC Setup
        run: |
          echo "Debugging OIDC setup..."
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Workflow: ${{ github.workflow }}"
          echo "GitHub Run ID: ${{ github.run_id }}"
          echo "OIDC permissions are enabled with id-token: write."

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/ci-cd-role
          aws-region: eu-central-1

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Print working directory
        run: pwd

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -var-file="./EKS_infra/envs/terraform_dev.tfvars"

      # - name: Apply Terraform
      #   run: terraform apply -auto-approve -var-file="EKS-BankingKube/EKS_infra/envs/terraform_dev.tfvars"