name: Deploy Dynamic Pod Sec

on:
  # You can also trigger on push or PR if you like
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC to assume your ci-cd-role
      contents: read
    env:
      AWS_ACCOUNT_ID: 961477247679
      AWS_REGION: eu-central-1
      EKS_CLUSTER_NAME: Banking-Kube-Sloth   # <-- Name of your EKS cluster
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/ci-cd-role
          aws-region: ${{ env.AWS_REGION }}

      # 1) Login to Amazon ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 2) Build & Push Docker Image
      - name: Build and Push Docker Image
        working-directory: BankingKube_app/Dynamic_Pod_Sec
        run: |
          IMAGE_NAME="banking-kube-repo"
          TAG=$(date +%Y%m%d%H%M%S)
          
          # Build the image locally
          docker build -t $IMAGE_NAME:$TAG .
          
          # Tag the image for ECR
          docker tag $IMAGE_NAME:$TAG ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$TAG
          
          # Push to ECR
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$TAG