name: Deploy Dynamic Pod Sec

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: 961477247679
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/ci-cd-role
          aws-region: eu-central-1

      - name: Login to ECR
        run: echo "simulating just"
        # uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=dynamic_pod_sec
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_NAME:$TAG .
          # docker tag $IMAGE_NAME:$TAG ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$TAG
          # docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$TAG
        env:
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
          AWS_REGION: eu-central-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.26.0"

      - name: Generate TLS Certificates
        run: bash scripts/generate-certs.sh

      - name: Deploy Webhook
        run: bash scripts/deploy-webhook.sh